version: '2'

# reference: https://blog.docker.com/2016/07/live-debugging-docker/

services:
  toodmvcjquery:
    build: .
    #NOTE: for the first time, you'll need to run the following command so that node_modules/ is generated
    #command: npm install
    # NOTE: thereafter you can just run the development mode server which auto detects changes to your project files
    command: nodemon --debug=5858
    volumes:
      - .:/app
    ports:
      - "8080:80"
      - "5858:5858"
    networks:
      net:
        ipv4_address: 172.18.21.10

networks:
  net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
      - subnet: 172.18.21.0/24
        gateway: 172.18.21.1

